insert into apex_usuario_perfil_datos (proyecto,nombre,descripcion,listar) values
('descentralizado','FACE ',null,null)
,('descentralizado','FAEA ',null,null)
,('descentralizado','FAIN ',null,null)
,('descentralizado','FATU ',null,null)
,('descentralizado','FAIF ',null,null)
,('descentralizado','FAAS ',null,null)
,('descentralizado','FATA ',null,null)
,('descentralizado','FAME ',null,null)
,('descentralizado','RECT ',null,null)
,('descentralizado','AUZA ',null,null)
,('descentralizado','FAHU ',null,null)
,('descentralizado','FACA ',null,null)
,('descentralizado','ESCM ',null,null)
,('descentralizado','CRUB ',null,null)
,('descentralizado','CUZA ',null,null)
,('descentralizado','VREC ',null,null)
,('descentralizado','SEHA ',null,null)
,('descentralizado','SEXU ',null,null)
,('descentralizado','SEGE ',null,null)
,('descentralizado','SEAC ',null,null)
,('descentralizado','SECT ',null,null)
,('descentralizado','SEPL ',null,null)
,('descentralizado','SUTI ',null,null)
,('descentralizado','SUVT ',null,null)
,('descentralizado','SURI ',null,null)
,('descentralizado','UAI  ',null,null)
,('descentralizado','IBMP ',null,null)
,('descentralizado','SEBU ',null,null)
,('descentralizado','SUAS ',null,null)
,('descentralizado','DPOS ',null,null)
,('descentralizado','BICE ',null,null)
,('descentralizado','MECO ',null,null);

insert into apex_usuario_perfil_datos_dims (proyecto,usuario_perfil_datos,dimension,clave)
select 'descentralizado', usuario_perfil_datos, 15, nombre from apex_usuario_perfil_datos where usuario_perfil_datos>28 and usuario_perfil_datos<70;
